name: 'build'

on: ['pull_request', 'push']

jobs:
  build:
    runs-on: 'ubuntu-latest'
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: 'checkout repo'
        uses: 'actions/checkout@v2'
      - name: 'setup JDK 1.8'
        uses: 'actions/setup-java@v1'
        with:
          java-version: 1.8
      - name: 'gradle build'
        run: './gradlew build'
      - name: 'gradle publish'
        run: './gradlew publish'
        env:
          REPO_USER: '${{ secrets.REPO_USER }}'
          REPO_PASSWORD: '${{ secrets.REPO_PASSWORD }}'
